var paycheck = 2000;
document.write(paycheck + "<BR>");
paycheck += 2000;
document.write(paycheck + "<BR>");
paycheck -= 500;
document.write(paycheck + "<BR>");
paycheck -= paycheck;
document.write(paycheck + "<BR>");
paycheck = paycheck + 500;
document.write(paycheck + "<BR>");
paycheck -= 80;
document.write(paycheck + "<BR>");
